#Hugo configuration
title = "Something else"
baseURL = "https:\/\/se.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
